### ISSUE TITLE
I get a  "No inport 'content' defined in process Parse (DATA -> CONTENT Parse())"

### ISSUE THREAD

**Issue by nicocesar** [noflo/noflo-jekyll#8]
I'm new to many things including  NoFlo, qhen I do: 

<pre>
 ./node_modules/.bin/noflo-jekyll kk jj
</pre>

  I get 

<pre>
/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:224
          throw new Error("No inport '" + port + "' defined in process " + pro
                ^
Error: No inport 'content' defined in process Parse (DATA -> CONTENT Parse())
    at Network.connectPort (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:224:17)
    at Network.addEdge (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:354:12)
    at Graph.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:350:24)
    at Graph.g (events.js:180:16)
    at Graph.EventEmitter.emit (events.js:117:20)
    at /home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/src/components/Graph.coffee:146:24
    at process._tickCallback (node.js:415:13)
</pre>

Seems  that is all broken! I get the same this 

<pre>
noflo list .
</pre>

How should I report this error? I follow http://noflojs.org/documentation/ for the installation, but I might have a set of version that could be difficult to reproduce. 

This is a Debian Jessie (Testing) since it includes npm

**Comment by bergie** [comment]
@nicocesar which NoFlo version do you have?

Right now we have the known issue noflo/noflo-routers#4 that blocks noflo-jekyll from working properly. It should be fixed soon.

**Comment by nicocesar** [comment]
according to  node_modules/noflo-jekyll/node_modules/noflo/package.json  it's 0.4.5 

I see your comment in noflo/noflo-routers#4   that noFlo 0.5 is out .  I'll try it out to see if that fixes  it.

**Comment by bergie** [comment]
@nicocesar we need to wait for @kenhkan to release the updated noflo-routers package. The component from it that we use in Jekyll has been broken for a while while he waited for 0.5

**Comment by nicocesar** [comment]
I see, m after update, I got the  "Error: No cache with key null to locate" that is mention in the other bug. 
Leaving the trace here for people with the same problem

<pre>
NoFlo Jekyll /home/ncesar/blog/kk -> /home/ncesar/blog/jj
/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-routers/node_modules/nohoarder/lib/cache_storage.coffee:103
        throw new Error("No cache with key " + key + " to locate");
              ^
Error: No cache with key null to locate
  at _ref (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-routers/node_modules/nohoarder/lib/cache_storage.coffee:58:17)
  at CacheStorage.locate (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-routers/node_modules/nohoarder/lib/cache_storage.coffee:104:9)
  at CacheStorage.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-routers/node_modules/nohoarder/lib/cache_storage.coffee:35:22)
  at Port.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-routers/components/GroupRouter.coffee:65:16)
  at Port.EventEmitter.emit (events.js:98:17)
  at InternalSocket.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-routers/node_modules/noflo/lib/Port.js:58:22)
  at InternalSocket.EventEmitter.emit (events.js:117:20)
  at InternalSocket.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InternalSocket.js:44:19)
  at /home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:112:25
  at Array.forEach (native)
  at Port.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:110:27)
  at GroupByObjectKey.getKey (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/components/GroupByObjectKey.coffee:55:19)
  at Port.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/components/GroupByObjectKey.coffee:19:15)
  at Port.EventEmitter.emit (events.js:98:17)
  at InternalSocket.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:67:22)
  at InternalSocket.EventEmitter.emit (events.js:117:20)
  at InternalSocket.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InternalSocket.js:44:19)
  at InternalSocket.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:115:25)
  at InternalSocket.g (events.js:180:16)
  at InternalSocket.EventEmitter.emit (events.js:117:20)
  at InternalSocket.connect (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InternalSocket.js:25:19)
  at /home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:117:23
  at Array.forEach (native)
  at Port.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:110:27)
  at Port.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/components/RemoveGroups.coffee:24:21)
  at Port.EventEmitter.emit (events.js:98:17)
  at InternalSocket.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:67:22)
  at InternalSocket.EventEmitter.emit (events.js:117:20)
  at InternalSocket.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InternalSocket.js:44:19)
  at InternalSocket.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-filesystem/node_modules/noflo/lib/Port.js:115:25)
  at InternalSocket.g (events.js:180:16)
  at InternalSocket.EventEmitter.emit (events.js:117:20)
  at InternalSocket.connect (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InternalSocket.js:25:19)
  at /home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-filesystem/node_modules/noflo/lib/Port.js:117:23
  at Array.forEach (native)
  at Port.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-filesystem/node_modules/noflo/lib/Port.js:110:27)
  at /home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-filesystem/components/Stat.coffee:25:21
  at Object.oncomplete (fs.js:107:15)
</pre>

Oh well I'll wait for  noflo/noflo-routers#4  to get closed.

**Comment by bergie** [comment]
@nicocesar thanks! I'll keep you posted on when this is fixed

**Comment by bergie** [comment]
Should be fixed now. Waiting for Travis to confirm in a clean environment and will then release a new version.

Please reopen if you still encounter issues after a clean git install

**Comment by nicocesar** [comment]
Now with noflo 0.5.0 and noflo-routers-0.2.0

I get: 

<pre>
$ ./node_modules/.bin/noflo-jekyll kk jj
NoFlo Jekyll /home/ncesar/blog/kk -> /home/ncesar/blog/jj
/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/OutPort.js:99
        throw new Error("" + (this.getId()) + ": No connections available");
              ^
Error: FileRouter ROUTE: No connections available
  at OutPort.checkRequired (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/OutPort.js:99:15)
  at OutPort.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/OutPort.js:55:12)
  at InPort.process (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-routers/components/GroupRouter.coffee:63:36)
  at InPort.handleSocketEvent (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InPort.js:82:16)
  at InternalSocket.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InPort.js:44:22)
  at InternalSocket.EventEmitter.emit (events.js:117:20)
  at InternalSocket.beginGroup (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InternalSocket.js:49:19)
  at InternalSocket.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:100:25)
  at InternalSocket.g (events.js:180:16)
  at InternalSocket.EventEmitter.emit (events.js:117:20)
  at InternalSocket.connect (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InternalSocket.js:25:19)
  at /home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:102:23
  at Array.forEach (native)
  at Port.beginGroup (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:95:27)
  at GroupByObjectKey.getKey (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/components/GroupByObjectKey.coffee:54:19)
  at Port.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/components/GroupByObjectKey.coffee:19:15)
  at Port.EventEmitter.emit (events.js:98:17)
  at InternalSocket.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:67:22)
  at InternalSocket.EventEmitter.emit (events.js:117:20)
  at InternalSocket.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InternalSocket.js:44:19)
  at InternalSocket.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:115:25)
  at InternalSocket.g (events.js:180:16)
  at InternalSocket.EventEmitter.emit (events.js:117:20)
  at InternalSocket.connect (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InternalSocket.js:25:19)
  at /home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:117:23
  at Array.forEach (native)
  at Port.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:110:27)
  at Port.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/components/RemoveGroups.coffee:24:21)
  at Port.EventEmitter.emit (events.js:98:17)
  at InternalSocket.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-groups/node_modules/noflo/lib/Port.js:67:22)
  at InternalSocket.EventEmitter.emit (events.js:117:20)
  at InternalSocket.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InternalSocket.js:44:19)
  at InternalSocket.<anonymous> (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-filesystem/node_modules/noflo/lib/Port.js:115:25)
  at InternalSocket.g (events.js:180:16)
  at InternalSocket.EventEmitter.emit (events.js:117:20)
  at InternalSocket.connect (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo/lib/InternalSocket.js:25:19)
  at /home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-filesystem/node_modules/noflo/lib/Port.js:117:23
  at Array.forEach (native)
  at Port.send (/home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-filesystem/node_modules/noflo/lib/Port.js:110:27)
  at /home/ncesar/blog/node_modules/noflo-jekyll/node_modules/noflo-filesystem/components/Stat.coffee:25:21
  at Object.oncomplete (fs.js:107:15)
</pre>

**Comment by bergie** [comment]
@nicocesar I pushed a fix for that, please git pull

**Comment by nicocesar** [comment]
I see.. I tried to make it work with git clone, but couldn’t   so I'll wait the new version at    https://www.npmjs.org/package/noflo-jekyll  (currently a 8month old 0.0.1 ... )
